[package]
authors = ["Composable Developers"]
edition = "2018"
homepage = "https://composable.finance"
name = "collator-sidecar"
version = "0.1.0"

[dependencies]
async-std = { version = "1", features = ["attributes", "tokio1"] }
env_logger = "0.8.4"
serde = { version = '1.0.136', features = ["derive"] }
structopt = "0.3.25"
tide = "0.16"
tokio = { version = "1.12.0", features = ["macros", "rt-multi-thread"] }
url = "1.7.0"

jsonrpsee = { version = "0.9", features = ["http-client", "macros"] }