cut_body_after = "## Checklist"
delete_merged_branches = true
required_approvals = 2
status = [
  "Check Benchmarks",
  "Unit Tests (With Coverage)",
  "Unit Tests",
  "Linters",
]
timeout_sec = 7200
up_to_date_approvals = true
update_base_for_deletes = true
use_codeowners = true
