[package]
name = "pallet-crowdloan-rewards"
version = "0.0.1"
authors = ["Composable Developers"]
homepage = "https://composable.finance"
edition = "2021"


[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies.codec]
default-features = false
features = ["derive"]
package = "parity-scale-codec"
version = "2.0.0"

[dev-dependencies]
serde = "1.0.130"
libsecp256k1 = { version = "0.7.0" }
hex-literal = "0.3.3"
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
pallet-balances = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
pallet-timestamp = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }

[dependencies]
# Benchmarking
hex-literal = { version = "0.3.3", optional = true }
libsecp256k1 = { version = "0.7.0", default-features = false, optional = true, features = ["hmac","static-context"] }
frame-benchmarking = { default-features = false, optional = true, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
sp-application-crypto = { default-features = false, optional = true, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }

# FRAME
frame-support = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
frame-system = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }

# substrate primitives
sp-runtime = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
sp-arithmetic = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
sp-io = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
sp-core = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
sp-std = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }

# SCALE
scale-info = { version = "1.0", default-features = false, features = ["derive"] }

# misc
serde = { version = "1.0.130", optional = true }
rustc-hex = { version = "2.1.0", default-features = false }
hex = { version = "0.4", default-features = false, features = ["alloc"] }

composable-traits = {  path = "../composable-traits", default-features = false }

[features]
default = ["std"]

std = [
    "codec/std",
    "frame-support/std",
    "frame-system/std",
    "sp-runtime/std",
    "sp-io/std",
    "sp-core/std",
    "sp-std/std",
    "sp-arithmetic/std",
    "scale-info/std",
    "serde/std",
]

runtime-benchmarks = [
    "hex-literal",
    "libsecp256k1",
    "frame-benchmarking",
    "sp-application-crypto",
    "frame-support/runtime-benchmarks",
    "frame-system/runtime-benchmarks",
]
