[package]
description = "tool to help with xcmp"
edition = "2021"
name = "xcmp"
version = "0.1.0"

[dependencies]
base58 = "0.2"
clap = { version = "3.2.5", features = ["derive"] }
composable-subxt = { default-features = false, path = "../composable-subxt" }
env_logger = "0.9.0"
hex = "0.4.3"
scale-codec = { package = "parity-scale-codec", version = "3.0.0", features = [
  "derive",
] }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.27", features = [
  "std",
  "full_crypto",
] }
sp-externalities = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.27" }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.27" }

sc-cli = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.27" }

sp-keyring = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.27" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.27", features = [
  "std",
] }
sp-runtime-interface = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.27" }
sp-std = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.27" }
subxt = { git = "https://github.com/paritytech/subxt", rev = "2fe9a1446d32b93a10804db3304ccaac65f764b8" }
tokio = { version = "1.23", features = ["rt-multi-thread", "macros", "time"] }
