[package]
name = "light-client-common"
version = "0.1.0"
edition = "2021"
authors = ["Seun Lanlege <seunlanlege@gmail.com>"]

[features]
default = ["std"]
std = [
    "anyhow/std",
    "codec/std",
    "primitive-types/std",
    "serde/std",
    "hash-db/std",
    "ibc/std",
    "sp-storage/std",
    "sp-trie/std",
]

[dependencies]
# crates.io
anyhow = { version = "1.0.65", default-features = false }
codec = { version = "3.2.1", package = "parity-scale-codec", default-features = false }
primitive-types = { version = "0.11.1", default-features = false }
serde = { version = "1.0.144", default-features = false, features = ["derive"] }
derive_more = { version = "0.99.17", default-features = false, features = ["from"] }
hash-db = { version = "0.15.2", default-features = false }

# ibc
ibc = { git = "https://github.com/ComposableFi/ibc-rs", rev = "70e3fa4bbb91f7b5893c1f1d2997ec46add1aad9", default-features = false }

# substrate
sp-storage = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.27", default-features = false }
sp-trie = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.27", default-features = false }
