version: '3'
services:
    node_alice:
        image: composablefi/composable:latest
        ports:
            - "30333:30333"
            - "9944:9944"
        volumes:
            - "polkadot-data-alice:/alice"
        command: node-template --telemetry-url 'ws://172.28.1.10:8000/submit 0' --validator --unsafe-ws-external --rpc-methods Unsafe --unsafe-rpc-external --ws-port 9944 --rpc-cors all --pruning archive --alice --node-key aa788920201122290fc7d3faf00698d9a8e061d7173424da2a31a8130a882a5f
        depends_on:
            - telemetry-backend
        networks:
            testing_net:
                ipv4_address: 172.28.1.1
    watchtower:
        image: "containrrr/watchtower"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ~/.docker/config.json:/config.json
        command: --interval 30

    node_bob:
        image: composablefi/composable
        ports:
            - "30334:30334"
            - "9945:9945"
        volumes:
            - "polkadot-data-bob:/bob"
        command: "node-template --telemetry-url 'ws://172.28.1.10:8000/submit 0' --validator --unsafe-ws-external --rpc-methods Unsafe --unsafe-rpc-external --rpc-cors all --ws-port 9945 --pruning archive --bob --bootnodes /ip4/172.28.1.1/tcp/30333/p2p/12D3KooWCJC43YRmb5WJcJmskPSxbkWY4Vp6jPKdFeggnXPxgBCw --port 30334"
        depends_on:
            - telemetry-backend
        networks:
            testing_net:
                ipv4_address: 172.28.1.2

    node_charlie:
        image: composablefi/composable
        ports:
            - "30335:30335"
            - "9946:9946"
        volumes:
            - "polkadot-data-charlie:/charlie"
        command: "node-template --telemetry-url 'ws://172.28.1.10:8000/submit 0' --validator --unsafe-ws-external --rpc-methods Unsafe --unsafe-rpc-external --rpc-cors all --ws-port 9946 --pruning archive --charlie --bootnodes /ip4/172.28.1.1/tcp/30333/p2p/12D3KooWCJC43YRmb5WJcJmskPSxbkWY4Vp6jPKdFeggnXPxgBCw --port 30335"
        depends_on:
            - telemetry-backend
        networks:
            testing_net:
                ipv4_address: 172.28.1.3

    node_dave:
        image: composablefi/composable
        ports:
            - "30336:30336"
            - "9947:9947"
        volumes:
            - "polkadot-data-dave:/dave"
        command: "node-template --telemetry-url 'ws://172.28.1.10:8000/submit 0' --validator --unsafe-ws-external --rpc-methods Unsafe --unsafe-rpc-external --rpc-cors all --ws-port 9947 --pruning archive --dave --bootnodes /ip4/172.28.1.1/tcp/30333/p2p/12D3KooWCJC43YRmb5WJcJmskPSxbkWY4Vp6jPKdFeggnXPxgBCw --port 30336"
        depends_on:
            - telemetry-backend
        networks:
            testing_net:
                ipv4_address: 172.28.1.4

    node_eve:
        image: composablefi/composable
        ports:
            - "30337:30337"
            - "9948:9948"
        volumes:
            - "polkadot-data-eve:/eve"
        command: "node-template --telemetry-url 'ws://172.28.1.10:8000/submit 0' --validator --unsafe-ws-external --rpc-methods Unsafe --unsafe-rpc-external --rpc-cors all --ws-port 9948 --pruning archive --eve --bootnodes /ip4/172.28.1.1/tcp/30333/p2p/12D3KooWCJC43YRmb5WJcJmskPSxbkWY4Vp6jPKdFeggnXPxgBCw --port 30337"
        depends_on:
            - telemetry-backend
        networks:
            testing_net:
                ipv4_address: 172.28.1.5

    node_ferdie:
        image: composablefi/composable
        ports:
            - "30338:30338"
            - "9949:9949"
        volumes:
            - "polkadot-data-ferdie:/ferdie"
        command: "node-template --telemetry-url 'ws://172.28.1.10:8000/submit 0' --validator --unsafe-ws-external --rpc-methods Unsafe --unsafe-rpc-external --rpc-cors all --ws-port 9949 --pruning archive --ferdie --bootnodes /ip4/172.28.1.1/tcp/30333/p2p/12D3KooWCJC43YRmb5WJcJmskPSxbkWY4Vp6jPKdFeggnXPxgBCw --port 30338"
        depends_on:
            - telemetry-backend
        networks:
            testing_net:
                ipv4_address: 172.28.1.6

    telemetry-backend:
        image: parity/substrate-telemetry-backend
        environment:
        - PORT=8000
        ports:
        - 8000:8000
        expose:
        - 8000
        command: --listen 0.0.0.0:8000
        networks:
            testing_net:
                ipv4_address: 172.28.1.10

    telemetry-frontend:
        image: parity/substrate-telemetry-frontend
        ports:
            - 3000:80
        environment:
            - SUBSTRATE_TELEMETRY_URL=ws://172.28.1.10:8000/feed
        networks:
            testing_net:
                ipv4_address: 172.28.1.11

    oracle:
        build:
            context: ./oracle
            dockerfile: Dockerfile
        volumes:
            - ./oracle:/app
        ports:
            - "3001:3001"
        networks:
            testing_net:
                ipv4_address: 172.28.1.13

volumes:
    polkadot-data-alice:
    polkadot-data-bob:
    polkadot-data-charlie:
    polkadot-data-dave:
    polkadot-data-eve:
    polkadot-data-ferdie:

networks:
    testing_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16
