[package]
authors = ["Composable developers"]
description = "RPC apis for substrate ibc"
edition = "2021"
license = "Apache-2.0"
name = "ibc-rpc"
publish = false
repository = "https://github.com/composablefi/substrate-ibc/"
version = "0.1.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", features = ["derive"] }
hex-literal = { version = "0.3.3" }
ibc-primitives = { path = "../primitives" }
jsonrpsee = { version = "0.13.0", features = ["server", "macros"] }
pallet-ibc = { path = ".." }
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.45"

frame-system = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }
ibc-proto = { git = "https://github.com/ComposableFi/ibc-rs", rev = "0438a753ac29c0b9711f00a2e33228d3d45ca5e3", default-features = false }
ibc-runtime-api = { path = "../runtime-api" }
sc-chain-spec = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }
sp-trie = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24" }
tendermint-proto = { git = "https://github.com/composableFi/tendermint-rs", rev = "5a74e0f8da4d3dab83cc04b5f1363b018cf3d9e8" }

[dependencies.ibc]
git = "https://github.com/ComposableFi/ibc-rs"
rev = "0438a753ac29c0b9711f00a2e33228d3d45ca5e3"
default-features = false
features = ["ics11_beefy"]