version: "3.9"

services:
  composable:
    image: composablefi/composable-sandbox:latest
    ports:
      - "9988:9988"
      - "9944:9944"
  integration-tests:
    image: node:bullseye
    command: ./DockerRun.sh
    working_dir: /code
    volumes:
      - .:/code
    environment:
      - ENDPOINT=composable:9988
    depends_on:
      - composable
