[package]
edition = "2021"
name = "utils-common"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
composable-runtime = { path = "../../runtime/composable" }
dali-runtime = { path = "../../runtime/dali" }
derive_more = "0.99.17"
picasso-runtime = { path = "../../runtime/picasso" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.27" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.27" }
system = { package = "frame-system", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.27" }
transaction-payment = { package = "pallet-transaction-payment", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.27" }
