[package]
edition = "2021"
name = "price-feed"
version = "0.1.0"


[dependencies]
binance = "0.18.3"
chrono = "0.4.19"
clap = { version = "3.1.12", features = ["derive"] }
custom_derive = "0.1.7"
enum_derive = "0.1.7"
env_logger = "0.9.0"
futures = "0.3.21"
jsonrpc-client-transports = "18.0.0"
jsonrpc-core = "18.0.0"
lazy_static = "1.4.0"
log = "0.4.16"
primitives = { path = "../../parachain/runtime/primitives" }
scale-codec = { package = "parity-scale-codec", version = "3.0.0", features = [
  "derive",
] }
serde = { version = '1.0.136', features = ["derive"] }
serde_json = "1.0.79"
signal-hook = "0.3.13"
signal-hook-tokio = { version = "0.3.1", features = ["futures-v0_3"] }
sp-arithmetic = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.33" }
subxt = { git = "https://github.com/paritytech/subxt", rev = "2a913a3aa99a07f7acaedbbaeed6925d34627303" }
tokio = { version = "1.18.0", features = ["full"] }
tokio-stream = "0.1.8"
url = "1.7.2"
warp = "0.3.2"
