[package]
edition = "2021"
name = "picasso-runtime"
version = "1.0.0"

authors = ["Seun Lanlege <seunlanlege@gmail.com>"]
description = "Picasso, Kusama Parachain Runtime Implementation"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[package.metadata.cargo-udeps.ignore]
normal = [
  "assets",
  "assets-registry",
  "call-filter",
  "currency-factory",
  "governance-registry",
  "oracle",
  "orml-unknown-tokens",
  "orml-xtokens",
  "pallet-bonded-finance",
  "pallet-vault",
  "session-benchmarking",
  "vault",
]

[dependencies]
executive = { package = "frame-executive", git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.33" }
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.33" }
frame-system = { package = "frame-system", git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.33" }

# primitives
sp-api = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.33" }
sp-block-builder = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.33" }
sp-consensus-aura = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.33" }
sp-core = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.33" }
sp-inherents = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.33" }
sp-offchain = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.33" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.33" }
sp-session = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.33" }
sp-std = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.33" }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.33" }
sp-version = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.33" }

# modules
aura = { package = "pallet-aura", git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.33" }
authorship = { package = "pallet-authorship", git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.33" }
balances = { package = "pallet-balances", git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.33" }
collective = { package = "pallet-collective", git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.33" }
democracy = { package = "pallet-democracy", git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.33" }
identity = { package = "pallet-identity", git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.33" }
indices = { package = "pallet-indices", git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.33" }
membership = { package = "pallet-membership", git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.33" }
multisig = { package = "pallet-multisig", git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.33" }
orml-tokens = { git = "https://github.com/open-web3-stack/open-runtime-module-library", branch = "polkadot-v0.9.33", default-features = false }
orml-traits = { git = "https://github.com/open-web3-stack/open-runtime-module-library", branch = "polkadot-v0.9.33", default-features = false }
preimage = { package = "pallet-preimage", git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.33" }
randomness-collective-flip = { package = "pallet-randomness-collective-flip", git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.33" }
scheduler = { package = "pallet-scheduler", git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.33" }
session = { package = "pallet-session", git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.33" }
smallvec = "1.6.1"
sudo = { package = "pallet-sudo", git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.33" }
timestamp = { package = "pallet-timestamp", git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.33" }
treasury = { package = "pallet-treasury", git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.33" }
utility = { package = "pallet-utility", git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.33" }


log = { version = "0.4.14", default-features = false }

# local modules
assets = { package = "pallet-assets", path = "../../frame/assets", default-features = false }
assets-registry = { package = "pallet-assets-registry", path = "../../frame/assets-registry", default-features = false }
bonded-finance = { package = "pallet-bonded-finance", path = "../../frame/bonded-finance", default-features = false }
call-filter = { package = "pallet-call-filter", path = "../../frame/call-filter", default-features = false }
common = { path = "../common", default-features = false }
composable-support = { path = "../../frame/composable-support", default-features = false }
composable-traits = { path = "../../frame/composable-traits", default-features = false }
crowdloan-rewards = { package = "pallet-crowdloan-rewards", path = "../../frame/crowdloan-rewards", default-features = false }
currency-factory = { package = "pallet-currency-factory", path = "../../frame/currency-factory", default-features = false }
governance-registry = { package = "pallet-governance-registry", path = "../../frame/governance-registry", default-features = false }
pablo = { package = "pallet-pablo", path = "../../frame/pablo", default-features = false }
primitives = { path = "../primitives", default-features = false }
vesting = { package = "pallet-vesting", path = "../../frame/vesting", default-features = false }
asset-tx-payment = { package = "pallet-asset-tx-payment", path = "../../frame/transaction-payment/asset-tx-payment", default-features = false }
transaction-payment = { package = "pallet-transaction-payment", path = "../../frame/transaction-payment", default-features = false }

# Used for the node template's RPCs
system-rpc-runtime-api = { package = "frame-system-rpc-runtime-api", git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.33" }
transaction-payment-rpc-runtime-api = { package = "pallet-transaction-payment-rpc-runtime-api", path = "../../frame/transaction-payment/rpc/runtime-api", default-features = false }

# local RPCs
assets-runtime-api = { path = "../../frame/assets/runtime-api", default-features = false }
crowdloan-rewards-runtime-api = { path = "../../frame/crowdloan-rewards/runtime-api", default-features = false }
pablo-runtime-api = { path = "../../frame/pablo/runtime-api", default-features = false }

# Used for runtime benchmarking
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = [
  "derive",
] }
frame-benchmarking = { git = "https://github.com/paritytech/substrate", default-features = false, optional = true, branch = "polkadot-v0.9.33" }
hex-literal = { version = "0.3.3", optional = true }
frame-system-benchmarking = { package = "frame-system-benchmarking", git = "https://github.com/paritytech/substrate", default-features = false, optional = true, branch = "polkadot-v0.9.33" }

# Parachain Utilities
collator-selection = { package = "pallet-collator-selection", git = "https://github.com/paritytech/cumulus", default-features = false, branch = "polkadot-v0.9.33" }
cumulus-pallet-aura-ext = { git = "https://github.com/paritytech/cumulus", default-features = false, branch = "polkadot-v0.9.33" }
cumulus-pallet-dmp-queue = { git = "https://github.com/paritytech/cumulus", default-features = false, branch = "polkadot-v0.9.33" }
cumulus-pallet-parachain-system = { git = "https://github.com/paritytech/cumulus", default-features = false, branch = "polkadot-v0.9.33" }
cumulus-pallet-xcm = { git = "https://github.com/paritytech/cumulus", default-features = false, branch = "polkadot-v0.9.33" }
cumulus-pallet-xcmp-queue = { git = "https://github.com/paritytech/cumulus", default-features = false, branch = "polkadot-v0.9.33" }
cumulus-primitives-core = { git = "https://github.com/paritytech/cumulus", default-features = false, branch = "polkadot-v0.9.33" }
cumulus-primitives-timestamp = { git = "https://github.com/paritytech/cumulus", default-features = false, branch = "polkadot-v0.9.33" }
cumulus-primitives-utility = { git = "https://github.com/paritytech/cumulus", default-features = false, branch = "polkadot-v0.9.33" }
pallet-xcm = { git = "https://github.com/paritytech/polkadot", default-features = false, branch = "release-v0.9.33" }
parachain-info = { git = "https://github.com/paritytech/cumulus", default-features = false, branch = "polkadot-v0.9.33" }
polkadot-parachain = { git = "https://github.com/paritytech/polkadot", default-features = false, branch = "release-v0.9.33" }
proxy = { package = "pallet-proxy", git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.33" }
scale-info = { version = "2.1.1", default-features = false, features = [
  "derive",
] }
session-benchmarking = { package = "cumulus-pallet-session-benchmarking", git = "https://github.com/paritytech/cumulus", default-features = false, branch = "polkadot-v0.9.33" }
xcm = { git = "https://github.com/paritytech/polkadot", default-features = false, branch = "release-v0.9.33" }
xcm-builder = { git = "https://github.com/paritytech/polkadot", default-features = false, branch = "release-v0.9.33" }
xcm-executor = { git = "https://github.com/paritytech/polkadot", default-features = false, branch = "release-v0.9.33" }

# orml XCM support
orml-unknown-tokens = { git = "https://github.com/open-web3-stack/open-runtime-module-library", branch = "polkadot-v0.9.33", default-features = false }
orml-xcm-support = { git = "https://github.com/open-web3-stack/open-runtime-module-library", branch = "polkadot-v0.9.33", default-features = false }
orml-xtokens = { git = "https://github.com/open-web3-stack/open-runtime-module-library", branch = "polkadot-v0.9.33", default-features = false }

# IBC support
ibc = { git = "https://github.com/ComposableFi/centauri", rev = "f0d44fe83c078b2d9fb040337c8152f037ba817d", default-features = false }
ibc-primitives = { git = "https://github.com/ComposableFi/centauri", rev = "f0d44fe83c078b2d9fb040337c8152f037ba817d", default-features = false }
ibc-runtime-api = { git = "https://github.com/ComposableFi/centauri", rev = "f0d44fe83c078b2d9fb040337c8152f037ba817d", default-features = false }
pallet-ibc = { git = "https://github.com/ComposableFi/centauri", rev = "f0d44fe83c078b2d9fb040337c8152f037ba817d", default-features = false }
pallet-ibc-ping = { git = "https://github.com/ComposableFi/centauri", rev = "f0d44fe83c078b2d9fb040337c8152f037ba817d", default-features = false }

[features]
builtin-wasm = []
default = ["std"]
local-integration-tests = []
runtime-benchmarks = [
  "balances/runtime-benchmarks",
  "frame-benchmarking",
  "frame-support/runtime-benchmarks",
  "frame-system-benchmarking/runtime-benchmarks",
  "frame-system/runtime-benchmarks",
  "hex-literal",
  "balances/runtime-benchmarks",
  "timestamp/runtime-benchmarks",
  "collective/runtime-benchmarks",
  "collator-selection/runtime-benchmarks",
  "session-benchmarking/runtime-benchmarks",
  "pallet-xcm/runtime-benchmarks",
  "sp-runtime/runtime-benchmarks",
  "xcm-builder/runtime-benchmarks",
  "indices/runtime-benchmarks",
  "identity/runtime-benchmarks",
  "multisig/runtime-benchmarks",
  "membership/runtime-benchmarks",
  "treasury/runtime-benchmarks",
  "scheduler/runtime-benchmarks",
  "collective/runtime-benchmarks",
  "democracy/runtime-benchmarks",
  "utility/runtime-benchmarks",
  "crowdloan-rewards/runtime-benchmarks",
  "currency-factory/runtime-benchmarks",
  "assets/runtime-benchmarks",
  "assets-registry/runtime-benchmarks",
  "vesting/runtime-benchmarks",
  "bonded-finance/runtime-benchmarks",
  "common/runtime-benchmarks",
  "asset-tx-payment/runtime-benchmarks",
  "proxy/runtime-benchmarks",
  "pablo/runtime-benchmarks",
  "pallet-ibc/runtime-benchmarks",

]
std = [
  "codec/std",
  "sp-api/std",
  "sp-std/std",
  "sp-core/std",
  "sp-runtime/std",
  "sp-version/std",
  "sp-offchain/std",
  "sp-session/std",
  "sp-block-builder/std",
  "sp-transaction-pool/std",
  "sp-inherents/std",
  "frame-support/std",
  "executive/std",
  "frame-system/std",
  "utility/std",
  "authorship/std",
  "balances/std",
  "randomness-collective-flip/std",
  "timestamp/std",
  "session/std",
  "sudo/std",
  "indices/std",
  "identity/std",
  "multisig/std",
  "call-filter/std",
  "orml-tokens/std",
  "orml-traits/std",
  "treasury/std",
  "democracy/std",
  "scheduler/std",
  "common/std",
  "primitives/std",
  "collective/std",
  "transaction-payment/std",
  "parachain-info/std",
  "cumulus-pallet-aura-ext/std",
  "cumulus-pallet-parachain-system/std",
  "cumulus-pallet-xcmp-queue/std",
  "cumulus-pallet-xcm/std",
  "cumulus-primitives-core/std",
  "cumulus-primitives-timestamp/std",
  "cumulus-primitives-utility/std",
  "collator-selection/std",
  "xcm/std",
  "xcm-builder/std",
  "xcm-executor/std",
  "aura/std",
  "sp-consensus-aura/std",
  "scale-info/std",
  "orml-xtokens/std",
  "orml-xcm-support/std",
  "orml-unknown-tokens/std",
  "composable-traits/std",
  "composable-support/std",
  "governance-registry/std",
  "currency-factory/std",
  "assets/std",
  "assets-registry/std",
  "vesting/std",
  "bonded-finance/std",
  "crowdloan-rewards/std",
  "preimage/std",
  "membership/std",
  "system-rpc-runtime-api/std",
  "transaction-payment-rpc-runtime-api/std",
  "assets-runtime-api/std",
  "crowdloan-rewards-runtime-api/std",
  "asset-tx-payment/std",
  "ibc/std",
  "pallet-ibc/std",
  "proxy/std",
  "pablo/std",
  "pablo-runtime-api/std",
  "pallet-ibc-ping/std",
  "ibc-primitives/std",
  "ibc-runtime-api/std",
]
