[package]
authors = ["Composable Developers"]
edition = "2021"
homepage = "https://composable.finance"
name = "collator-sidecar"
version = "0.1.0"

[dependencies]
async-std = { version = "1.9.0", features = ["attributes", "tokio1"] }
env_logger = "0.9.0"
serde = { version = '1.0.136', features = ["derive"] }
structopt = "0.3.26"
tide = "0.17.0-beta.1"
tokio = { version = "1.18.0", features = ["macros", "rt-multi-thread"] }

jsonrpsee = { version = "0.11.0", features = ["http-client", "macros"] }
