repos:
- repo: local
  hooks:
  - id: fmt
    name: cargo-fmt
    entry: cargo +nightly fmt --check -p pallet-vamm
    language: system
    pass_filenames: false
    stages: [commit, push]
  - id: check
    name: cargo-check
    entry: cargo +nightly check --all-targets -p pallet-vamm
    language: system
    pass_filenames: false
    stages: [commit, push]
  - id: test
    name: cargo-test
    entry: cargo +nightly test --all-features --tests -p pallet-vamm
    language: system
    pass_filenames: false
    stages: [push]
  - id: clippy
    name: cargo-clippy
    entry: cargo +nightly clippy --all-targets --no-deps -p pallet-vamm
    language: system
    pass_filenames: false
    stages: [push]
- repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  rev: v8.0.0
  hooks:
  - id: commitlint
    stages: [commit-msg]
    additional_dependencies: ['@commitlint/config-conventional']
