[package]
name = "pallet-ibc-ping"
version = "0.0.1"
authors = ["Composable Developers"]
homepage = "https://composable.finance"
edition = "2021"

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
log = { version = "0.4.0", default-features = false }
serde = { version = "1.0.136", default-features = false, features = ["derive"] }
scale-info = { version = "1.0", default-features = false, features = ["derive"] }

frame-support = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17", default-features = false }
frame-system = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17", default-features = false }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17", default-features = false }

#ibc = { version = "0.13.0", default-features = false }
ibc = { git = "https://github.com/informalsystems/ibc-rs.git", branch = "master", default-features = false }
ibc-trait = {path = "../ibc/ibc-trait", default-features = false }
ibc-primitives = {path = "../ibc/ibc-primitives", default-features = false }

[dev-dependencies]
pallet-ibc = { path = "../ibc" }
balances = { package = "pallet-balances", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
tendermint-proto = { version = "0.23.6" }
ibc = { git = "https://github.com/informalsystems/ibc-rs.git", branch = "master", features = ["mocks"] }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }

[features]
default = ['std']
std = [
    "codec/std",
    "log/std",
    "serde/std",
    "scale-info/std",
    "sp-core/std",
    "sp-runtime/std",
    "frame-system/std",
    "frame-support/std",
    "sp-std/std",
    "ibc/std",
    "ibc-trait/std",
    "ibc-primitives/std"
]

runtime-benchmarks = []