[package]
edition = "2021"
name = "ibc-runtime-api"
version = "0.1.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
ibc-primitives = { path = "../ibc-primitives", default-features = false }
pallet-ibc = { path = "../", default-features = false }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24", default-features = false }
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = [
  "derive",
] }

[features]
default = ['std']
std = ['sp-api/std', 'sp-std/std', 'ibc-primitives/std', 'pallet-ibc/std', 'codec/std']
