[profile.default]
libs = ['lib', 'node_modules']
out = 'out'
remappings = [
  '/node_modules/@ensdomains/=@ensdomains/',
  '/node_modules/@lazyledger/=@lazyledger/',
  '/node_modules/@openzeppelin/=@openzeppelin/',
  '/node_modules/@prb/=@prb/',
  'ds-test/=lib/forge-std/lib/ds-test/src/',
  'forge-std/=lib/forge-std/src/',
  'hardhat/=node_modules/hardhat/',
]
src = 'src'


# See more config options https://github.com/foundry-rs/foundry/tree/master/config
