[package]
description = "Generates subxt clients to arbitrary substrate chains and provides Composable clients and configurations"
edition = "2021"
name = "composable-subxt"
version = "0.1.0"

[[bin]]
name = "codegen"

[dependencies]
base58 = "0.2"
clap = { version = "3.2.5", features = ["derive", "env"] }
env_logger = "0.9.0"
hex = "0.4.3"
scale-codec = { package = "parity-scale-codec", version = "3.0.0", features = [
  "derive",
] }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.27", features = [
  "std",
  "full_crypto",
] }

subxt = { git = "https://github.com/paritytech/subxt", rev = "2fe9a1446d32b93a10804db3304ccaac65f764b8" }

sp-externalities = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.27" }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.27" }
sp-runtime-interface = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.27" }
sp-std = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.27" }
tokio = { version = "1.23", features = ["rt-multi-thread", "macros", "time"] }

[build-dependencies]
clap = { version = "3.2.5", features = ["derive", "env"] }
