[package]
name = "hyperspace"
version = "0.1.0"
edition = "2021"
authors = ["Composable Developers"]

[[bin]]
name = "hyperspace"
path = "./bin/main.rs"

[dependencies]
primitives = { path = "primitives", package = "hyperspace-primitives" }
parachain = { path = "parachain", package = "hyperspace-parachain", optional = true }
cosmos = { path = "cosmos", package = "hyperspace-cosmos", optional = true }
#near = { path = "near", package = "hyperspace-near", optional = true }
metrics = { path = "metrics" }

# crates.io
anyhow = "1.0.65"
futures = "0.3.21"
async-trait = "0.1.53"
log = "0.4.17"
env_logger = "0.9.0"
hex = "0.4.3"
tokio = { version = "1.19.2", features = ["macros", "rt-multi-thread", "fs"] }
codec = { version = "3.0.0", package = "parity-scale-codec" }
clap = { version = "3.2.22", features = ["derive"] }
toml = "0.5.9"
serde = "1.0.144"
thiserror = "1.0.31"
derive_more = { version = "0.99.17", features = ["from"] }
prometheus = { version = "0.13.0", default-features = false }

# ibc
ibc = { path = "../ibc/modules", features = [] }
ibc-proto = { path = "../ibc/proto" }
tendermint-proto = { git = "https://github.com/composableFi/tendermint-rs", rev = "5a74e0f8da4d3dab83cc04b5f1363b018cf3d9e8" }
ibc-rpc = { path = "../../parachain/frame/ibc/rpc" }

ics11-beefy = { path = "../light-clients/ics11-beefy" }
ics13-near = { path = "../light-clients/ics13-near" }
light-client-common = { path = "../light-clients/common" }
pallet-ibc = { path = "../../parachain/frame/ibc" }
ics10-grandpa = { path = "../light-clients/ics10-grandpa" }

sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.27" }
sc-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.27" }
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.27" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.27" }
subxt = { git = "https://github.com/paritytech/subxt", rev = "51179a8b72472d0b43c91cda75a1ddc3fddb9555", optional = true }

subxt-codegen = { path = "../../../utils/subxt-codegen" }

[dev-dependencies]
derive_more = "0.99.17"
prost = "0.10"
parachain = { path = "parachain", package = "hyperspace-parachain", features = ["testing"] }

# substrate
subxt = { git = "https://github.com/paritytech/subxt", rev = "51179a8b72472d0b43c91cda75a1ddc3fddb9555" }
frame-support = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.27" }
sp-trie = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.27" }
state-machine = { package = "sp-state-machine", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.27" }
sp-keyring = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.27" }

# composable
#comosable-primitives = { package = "primitives",  path = "../../parachain/frame/ibc" }
#common = { path = "../../parachain/frame/ibc" }

[features]
parachain = ["dep:parachain", "subxt"]
#near = ["dep:near"]
#cosmos = ["dep:cosmos"]
testing = []