[package]
name = "simnode-node"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
substrate-simnode = { git = "https://github.com/polytope-labs/substrate-simnode", branch = "master"}
common = { package = "simnode-common", path = "../common" }
node = { package = "composable-node", path = "../../../node", features = ["dali"] }

sc-cli = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.17" }
structopt = "0.3.25"