[package]
name = "parachain-utils"
version = "0.1.0"
authors = ["Composable Developers"]
homepage = "https://composable.finance"
edition = "2018"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
env_logger = "0.8.4"
log = "0.4.14"
url = "1.7"
sp-runtime = {  git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.12" }
derive_more = "0.99.16"
tokio = {version = "1", features = ["full"]}
codec = { package = "parity-scale-codec", version = "2.2.0", default-features = false }
envy = "0.4.2"
serde = { version = "1", features = ["derive"] }

jsonrpc-core-client = { version = "18", features = ["http", "ws"] }
structopt = "0.3.23"
sc-rpc = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.12" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.12" }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.12" }

common = { package = "common", path = "../../runtime/common" }
subxt = { git = "https://github.com/composableFi/subxt", branch = "seun-0.9.12" }
subxt-clients = { path = "../subxt-clients" }
