[package]
name = "parachain-utils"
version = "0.1.0"
authors = ["Composable Developers"]
homepage = "https://composable.finance"
edition = "2018"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
env_logger = "0.8.4"
log = "0.4.14"
url = "1.7"
sp-runtime = {  git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.12" }
substrate-frame-rpc-system = {  git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.12" }
transaction-payment = { package = "pallet-transaction-payment", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.12" }
system = { package = "frame-system", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.12" }
balances = { package = "pallet-balances", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.12" }
scheduler = { package = "pallet-scheduler", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.12" }
sudo = { package = "pallet-sudo", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.12" }

rococo = { package = "rococo-runtime", git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.12" }
polkadot-core-primitives = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.12" }
session = { package = "pallet-session", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.12" }

futures = {version = "0.3", features = ["compat"]}
jsonrpc-core-client = { version = "18", features = ["http", "ws"] }
structopt = "0.3.23"
sc-rpc = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.12" }
sp-rpc = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.12" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.12" }

tokio = {version = "1", features = ["full"]}
codec = { package = "parity-scale-codec", version = "2.2.0", default-features = false }
envy = "0.4.2"
serde = { version = "1", features = ["derive"] }

picasso = { package = "picasso-runtime", path = "../../runtime/picasso" }
common = { package = "common", path = "../../runtime/common" }
