[package]
authors = ["Composable Developers"]
edition = "2018"
homepage = "https://composable.finance"
name = "parachain-utils"
version = "0.1.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false }
derive_more = "0.99.16"
env_logger = "0.8.4"
log = "0.4.14"
parachain-system = { package = "cumulus-pallet-parachain-system", git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.19" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.19" }
system = { package = "frame-system", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.19" }
tokio = { version = "1", features = ["full"] }
transaction-payment = { package = "pallet-transaction-payment", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.19" }
url = "1.7.0"

jsonrpc-core-client = { version = "18", features = ["ws"] }
sc-rpc = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.19" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.19" }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.19" }
structopt = "0.3.23"

sudo = { package = "pallet-sudo", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.19" }

common = { package = "common", path = "../../runtime/common" }
substrate-xt = { git = "https://github.com/polytope-labs/substrate-xt", rev = "cc9ce2d8651c2d140ae45f1de67faf792c5cda96" }

utils-common = { path = "../common" }

# runtimes
composable-runtime = { path = "../../runtime/composable" }
dali-runtime = { path = "../../runtime/dali" }
picasso-runtime = { path = "../../runtime/picasso" }

[dev-dependencies]
hex = "0.4.3"
