[package]
edition = "2021"
name = "picasso-runtime-wasm"
version = "1.10000.0"

authors = ["Hussein Ait Lahcen <hussein.aitlahcen@gmail.com>"]
description = "Picasso, Kusama Parachain Runtime WASM Implementation"

[dependencies]
picasso-runtime = { path = "../picasso/", default-features = false }

[lib]
crate-type = ["cdylib"]
name = "picasso_runtime"

[features]
runtime-benchmarks = ["picasso-runtime/runtime-benchmarks"]
