[package]
name = "pallet-assets"
version = "0.0.1"
authors = ["Composable Developers"]
homepage = "https://composable.finance"
edition = "2018"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
frame-support = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.10"  }
frame-system = { default-features = false,  git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.10" }

sp-runtime = { default-features = false,  git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.10" }
sp-arithmetic = { default-features = false,  git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.10" }
sp-io = {  default-features = false,  git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.10" }
sp-core = {  default-features = false,  git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.10" }
sp-std = {  default-features = false,  git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.10" }

composable-traits = { version = "0.0.1", path = "../composable-traits", default-features = false }
orml-traits = { git = "https://github.com/open-web3-stack/open-runtime-module-library", default-features = false }
num-traits = {version = "0.2.14", default-features = false}

composable-traits = { version = "0.0.1", path = "../composable-traits", default-features = false }

[dependencies.codec]
default-features = false
features = ["derive"]
package = "parity-scale-codec"
version = "2.0.0"

[features]
default = ["std"]
std = [
    "codec/std",
    "frame-support/std",
    "sp-runtime/std",
    "orml-traits/std",
    "num-traits/std"
]
