[package]
edition = "2021"
name = "simnode-node"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { package = "simnode-common", path = "../parachain/common" }
node = { package = "composable-node", path = "../../parachain/node", features = [
  "dali",
] }
substrate-simnode = { git = "https://github.com/polytope-labs/substrate-simnode", branch = "polkadot-v0.9.33" }

sc-cli = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.33" }
