name: "Release Rollout"

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Network Environment
        options:
          - dali
          - picasso
          - composable

jobs:
  dali-client-release:
    if: github.event.inputs.name == 'dali'
    runs-on:
      - self-hosted
      - linux
      - X64
      - ansible-runner
    steps:
      - name: Clean up
        continue-on-error: true
        run: |
          sudo chown -R $USER:$USER $GITHUB_WORKSPACE
          docker system prune --force --all --volumes
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set env
        run: |
          echo "RELEASE_VERSION=$(git tag --sort=committerdate | grep -E '^v[0-9]' | tail -1 )" >> $GITHUB_ENV
      - name: Run ansible playbook
        working-directory: "./.maintain/playbooks"
        run: |
          ansible-playbook -l _environment_testnet client-upgrade.yml -i gcp.yaml  --user root -e 'ansible_python_interpreter=/usr/bin/python3'
      - name: Notify sre-tasks slack channel
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_CHANNEL: releases
          SLACK_USERNAME: Github Actions
          SLACK_ICON: https://avatars.githubusercontent.com/u/44036562?s=200&v=4
          SLACK_TITLE: A new composable client for Dali-rococo ${{ env.RELEASE_VERSION }} has been rolled out
          SLACK_MESSAGE: "https://telemetry.polkadot.io/#list/0x5719ed0c1a5f4a11ef4d206f3a35d350365adc35943f2834b8d5bc7ff6e1a1d2"
          SLACK_FOOTER: ""
          MSG_MINIMAL: true

  picasso-client-release:
    if: github.event.inputs.name == 'picasso'
    concurrency:
      group: picasso-${{ github.ref }}
      cancel-in-progress: true
    strategy:
      fail-fast: true
    runs-on:
      - self-hosted
      - linux
      - X64
      - ansible-runner

    steps:
      - name: Clean up
        continue-on-error: true
        run: |
          sudo chown -R $USER:$USER $GITHUB_WORKSPACE && sudo chmod -R 777 /home/runner/_work/_tool/node/16.14.0
          docker system prune --force --all --volumes
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set env
        run: |
          echo "RELEASE_VERSION=$(git tag --sort=committerdate | grep -E '^v[0-9]' | tail -1 )" >> $GITHUB_ENV
      - name: Run ansible playbook
        working-directory: "./.maintain/playbooks"
        run: |
          ansible-playbook -l _environment_canary client-upgrade.yml -i picasso-gcp.yaml  --user root -e 'ansible_python_interpreter=/usr/bin/python3'
      - name: Notify sre-tasks slack channel
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: releases
          SLACK_USERNAME: Github Actions
          SLACK_ICON: https://avatars.githubusercontent.com/u/44036562?s=200&v=4
          SLACK_TITLE: A new composable client for Picasso ${{ env.RELEASE_VERSION }} has been rolled out
          SLACK_MESSAGE: "https://telemetry.polkadot.io/#list/0x6811a339673c9daa897944dcdac99c6e2939cc88245ed21951a0a3c9a2be75bc"
          SLACK_FOOTER: ""
          MSG_MINIMAL: true

  composable-client-release:
    if: github.event.inputs.name == 'composable'
    concurrency:
      group: composable-${{ github.ref }}
      cancel-in-progress: true
    strategy:
      fail-fast: true
    runs-on:
      - self-hosted
      - linux
      - X64
      - ansible-runner
    steps:
      - name: Clean up
        continue-on-error: true
        run: |
          sudo chown -R $USER:$USER $GITHUB_WORKSPACE && sudo chmod -R 777 /home/runner/_work/_tool/node/16.14.0
          docker system prune --force --all --volumes
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set env
        run: |
          echo "RELEASE_VERSION=$(git tag --sort=committerdate | grep -E '^v[0-9]' | tail -1 )" >> $GITHUB_ENV
      - name: Run ansible playbook
        working-directory: "./.maintain/playbooks"
        run: |
          ansible-playbook -l _environment_mainnet /opt/ansible/inventory/client-upgrade.yml -i /opt/ansible/inventory/composable-gcp.yaml  --user root -e 'ansible_python_interpreter=/usr/bin/python3'
      - name: Notify sre-tasks slack channel
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: releases
          SLACK_USERNAME: Github Actions
          SLACK_ICON: https://avatars.githubusercontent.com/u/44036562?s=200&v=4
          SLACK_TITLE: A new composable client for Composable ${{ env.RELEASE_VERSION }} has been rolled out
          SLACK_MESSAGE: "https://telemetry.polkadot.io/#list/0x6811a339673c9daa897944dcdac99c6e2939cc88245ed21951a0a3c9a2be75bc"
          SLACK_FOOTER: ""
          MSG_MINIMAL: true