name: Runtime Release
on:
  push:
    branches:
      - 'release/**'

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - id: release
        uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: major # if PR contains "release:major; release:minor or release:patch" - this is overwritten
          tag_prefix: v 
        #   release_body: "When set, adds extra text to body!" #you can customize the release body

  docker-build:
    runs-on: 
      - self-hosted
      - linux
      - x64
      - sre
    steps:
      - uses: actions/checkout@v2
        with: 
          fetch-depth: 0
      - name: Set env
        run: echo "RELEASE_VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))" >> $GITHUB_ENV

      - name: Download rococo-chachacha.json
        run: |
          docker system prune -f 
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ./docker/get-rococo get s3://composable-rococo/rococo-chachacha.json rococo-chachacha.json

      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
          
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Artifacts to gcloud
        run: |
          /home/composable/.cargo/bin/cargo build --release -p composable
          gsutil cp composable/target/release/composable gs://composable-binaries/releases/client/v0.1.0/

      - name: Set up Docker Build
        run: |
          make containerize

      - name: Docker push
        run: |
          make push

  # binary-build: 
  #   runs-on: 
  #     - self-hosted
  #     - linux
  #     - x64
  #     - sre  
  #   steps:
  #     - uses: actions/checkout@v2
  #       with: 
  #         fetch-depth: 0

  #     - name: Set env
  #       run: echo "RELEASE_VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))" >> $GITHUB_ENV

  #     - name: Download rococo-chachacha.json
  #       run: |
  #         export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
  #         export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         ./docker/get-rococo get s3://composable-rococo/rococo-chachacha.json rococo-chachacha.json
        
  #     - name: Build composable
  #       run: cargo build --release -p composable

  #     - name: Copy Build Artifacts
  #       run: |
  #         export FILENAME='faucet-server'${RELEASE_VERSION}
  #         zip faucet-server${RELEASE_VERSION}  target/release/faucet-server
  #         aws s3 cp $FILENAME s3://advancedblockchain.binaries
  


      